# Generated by Django 3.2 on 2021-05-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=25)),
                ('price', models.FloatField()),
                ('img', models.FileField(upload_to='')),
            ],
        ),
    ]
