# Generated by Django 3.2 on 2021-05-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=6)),
                ('is_active', models.IntegerField(max_length=1)),
            ],
        ),
    ]
